// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build
part of 'quran_surah.dart';

QuranSurah _$QuranSurahFromJson(Map<String, dynamic> json) => QuranSurah(
      id: json['id'] as int,
      name: json['name'] as String,
      transliteration: json['transliteration'] as String?,
      translation: json['translation'] as String?,
      type: json['type'] as String,
      ayahCount: json['ayah_count'] as int,
      ayahs: (json['ayahs'] as List<dynamic>?)
          ?.map((e) => QuranAyah.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$QuranSurahToJson(QuranSurah instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'transliteration': instance.transliteration,
      'translation': instance.translation,
      'type': instance.type,
      'ayah_count': instance.ayahCount,
      'ayahs': instance.ayahs,
    };

QuranAyah _$QuranAyahFromJson(Map<String, dynamic> json) => QuranAyah(
      id: json['id'] as int,
      text: json['text'] as String,
      page: json['page'] as int?,
      juz: json['juz'] as int?,
      manzil: json['manzil'] as int?,
      ruku: json['ruku'] as int?,
      hizbQuarter: json['hizb_quarter'] as int?,
      sajda: json['sajda'] as bool?,
    );

Map<String, dynamic> _$QuranAyahToJson(QuranAyah instance) =>
    <String, dynamic>{
      'id': instance.id,
      'text': instance.text,
      'page': instance.page,
      'juz': instance.juz,
      'manzil': instance.manzil,
      'ruku': instance.ruku,
      'hizb_quarter': instance.hizbQuarter,
      'sajda': instance.sajda,
    };

QuranSurahsList _$QuranSurahsListFromJson(Map<String, dynamic> json) =>
    QuranSurahsList(
      surahs: (json['surahs'] as List<dynamic>)
          .map((e) => QuranSurah.fromJson(e as Map<String, dynamic>))
          .toList(),
      total: json['total'] as int,
      language: json['language'] as String,
    );

Map<String, dynamic> _$QuranSurahsListToJson(QuranSurahsList instance) =>
    <String, dynamic>{
      'surahs': instance.surahs,
      'total': instance.total,
      'language': instance.language,
    };
